{{- if .Values.serviceAccount }}
{{- if .Values.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-sa
  labels:
    app: {{ .Values.name }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
