{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "online-boutique-service.fullname" . }}-access
  labels:
    {{- include "online-boutique-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "online-boutique-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- range .Values.networkPolicy.allowedPods }}
    - from:
        - podSelector:
            matchLabels:
              {{- toYaml . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ $.Values.service.port }}
    {{- end }}
{{- end }}