apiVersion: v1
kind: Service
metadata:
  name: {{ include "online-boutique-service.fullname" . }}
  labels:
    {{- include "online-boutique-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      {{- if or (eq (.Values.service.port | int) 8080) (eq (.Values.service.port | int) 80) }}
      name: http
      {{- else }}
      name: grpc
      {{- end }}
  selector:
    {{- include "online-boutique-service.selectorLabels" . | nindent 4 }}
