{{- if .Values.useStatefulSet }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "online-boutique-service.fullname" . }}
  labels:
    {{- include "online-boutique-service.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "online-boutique-service.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "online-boutique-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "online-boutique-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "online-boutique-service.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: {{ include "online-boutique-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if or .Values.configMap.create .Values.secrets.create }}
          envFrom:
          {{- if .Values.configMap.create }}
            - configMapRef:
                name: {{ include "online-boutique-service.fullname" . }}-config
          {{- end }}
          {{- if .Values.secrets.create }}
            - secretRef:
                name: {{ include "online-boutique-service.fullname" . }}-secret
          {{- end }}
          {{- end }}
          {{- if and .Values.env (not .Values.configMap.create) }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: {{ include "online-boutique-service.fullname" . }}-data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "online-boutique-service.fullname" . }}-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
{{- end }}