apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-online-boutique-service
  namespace: online-boutique-dev
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: currencyservice
          image: gcr.io/google-samples/microservices-demo/currencyservice:v0.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"                # ← indispensable pour que le service démarre sur le bon port
            - name: DISABLE_PROFILER
              value: "1"
            - name: CART_SERVICE_ADDR
              value: "cart-online-boutique-service:7070"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalog-online-boutique-service:3550"
            - name: PAYMENT_SERVICE_ADDR
              value: "payment-online-boutique-service:5050"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendation-online-boutique-service:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "shipping-online-boutique-service:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkout-online-boutique-service:5050"
            - name: AD_SERVICE_ADDR
              value: "ad-online-boutique-service:9555"
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "150m"
              memory: "128Mi"
          livenessProbe:
            grpc:
              port: 7000
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            grpc:
              port: 7000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: currency-online-boutique-service
  namespace: online-boutique-dev
spec:
  type: ClusterIP
  ports:
    - port: 7000
      targetPort: 7000
  selector:
    app: currencyservice
