{{- define "online-boutique-service.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - containerPort: {{ .port }}
        env:
          - name: PORT
            value: "{{ .port }}"
          - name: DISABLE_PROFILER
            value: "1"
          {{- if eq .name "frontend" }}
          - name: CART_SERVICE_ADDR
            value: "dev-cartservice-online-boutique-service:{{ $.Values.service.cart }}"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "dev-productcatalogservice-online-boutique-service:{{ $.Values.service.productcatalog }}"
          - name: PAYMENT_SERVICE_ADDR
            value: "dev-checkoutservice-online-boutique-service:{{ $.Values.service.checkout }}"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "dev-recommendationservice-online-boutique-service:{{ $.Values.service.recommendation }}"
          - name: SHIPPING_SERVICE_ADDR
            value: "dev-shippingservice-online-boutique-service:{{ $.Values.service.shipping }}"
          - name: CHECKOUT_SERVICE_ADDR
            value: "dev-checkoutservice-online-boutique-service:{{ $.Values.service.checkout }}"
          - name: AD_SERVICE_ADDR
            value: "dev-adservice-online-boutique-service:{{ $.Values.service.ad }}"
          - name: EMAIL_SERVICE_ADDR
            value: "dev-emailservice-online-boutique-service:{{ $.Values.service.email }}"
          - name: CURRENCY_SERVICE_ADDR
            value: "dev-currencyservice-online-boutique-service:{{ $.Values.service.currency }}"
          - name: SHOPPING_ASSISTANT_SERVICE_ADDR
            value: "dev-shoppingassistantservice-online-boutique-service:{{ $.Values.service.shoppingassistant }}"
          {{- end }}
        resources:
          limits:
            cpu: {{ $.Values.resources.limits.cpu }}
            memory: {{ $.Values.resources.limits.memory }}
          requests:
            cpu: {{ $.Values.resources.requests.cpu }}
            memory: {{ $.Values.resources.requests.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
  - port: {{ .port }}
    targetPort: {{ .port }}
{{- end }}
