{{- if .Values.secret }}
{{- if .Values.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  labels:
    app: {{ .Values.name }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
