apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Namespace ArgoCD
  - namespace.yaml
  
  # Installation ArgoCD via URL officielle
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  
  # Default AppProject
  - appproject.yaml
  
  # Secret pour accès GitLab
  - argocd-repo-secret.yaml

# Remplace les SSH known hosts par défaut avec gitlab.esiea.fr
configMapGenerator:
  - name: argocd-ssh-known-hosts-cm
    behavior: replace
    files:
      - ssh_known_hosts
