replicaCount: 1

image:
  frontend:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    tag: v0.10.4
    pullPolicy: IfNotPresent
  currency:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
    tag: v0.10.4
    pullPolicy: IfNotPresent
  productcatalog:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
    tag: v0.10.4
    pullPolicy: IfNotPresent
  cart:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
    tag: v0.10.4
    pullPolicy: IfNotPresent
  checkout:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
    tag: v0.10.4
    pullPolicy: IfNotPresent
  recommendation:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
    tag: v0.10.4
    pullPolicy: IfNotPresent
  shipping:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
    tag: v0.10.4
    pullPolicy: IfNotPresent
  ad:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
    tag: v0.10.4
    pullPolicy: IfNotPresent
  email:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
    tag: v0.10.4
    pullPolicy: IfNotPresent
  shoppingassistant:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/shoppingassistantservice
    tag: v0.10.4
    pullPolicy: IfNotPresent

service:
  cart: 7070
  productcatalog: 80          # correspond au ClusterIP du service
  checkout: 80                # correspond au ClusterIP du service
  recommendation: 8080
  shipping: 50051
  ad: 9555
  email: 2500
  currency: 80                # correspond au ClusterIP du service
  shoppingassistant: 6060

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"
