apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  # Applications DEV uniquement
  - adservice.yaml
  - cartservice.yaml
  - checkoutservice.yaml
  - currencyservice.yaml
  - emailservice.yaml
  - frontend.yaml
  - loadgenerator.yaml
  - paymentservice.yaml
  - productcatalogservice.yaml
  - recommendationservice.yaml
  - redis-cart.yaml
  - shippingservice.yaml
  # Note: Les apps PROD ne sont PAS incluses ici

namespace: argocd
